package cn.com.thinkwatch.ihass2.model

import cn.com.thinkwatch.ihass2.model.datatype.KeyValues
import cn.com.thinkwatch.ihass2.utils.AlwaysListTypeAdapterFactory
import com.google.gson.annotations.JsonAdapter
import com.google.gson.annotations.SerializedName
import java.math.BigDecimal
import java.util.*

class Attribute(@SerializedName("entity_id") @JsonAdapter(AlwaysListTypeAdapterFactory::class) var entityIds: ArrayList<String>? = null,
                @SerializedName("next_dawn") @Metadata(name = "下次黎明", display = "cn.com.thinkwatch.ihass2.utils.ZonedDateAsTime") var nextDawn: String? = null,
                @SerializedName("next_dusk") @Metadata(name = "下次黄昏", display = "cn.com.thinkwatch.ihass2.utils.ZonedDateAsTime") var nextDusk: String? = null,
                @SerializedName("next_midnight") @Metadata(name = "下次午夜", display = "cn.com.thinkwatch.ihass2.utils.ZonedDateAsTime") var nextMidnight: String? = null,
                @SerializedName("next_noon") @Metadata(name = "下次正午", display = "cn.com.thinkwatch.ihass2.utils.ZonedDateAsTime") var nextNoon: String? = null,
                @SerializedName("next_rising") @Metadata(name = "下次日出", display = "cn.com.thinkwatch.ihass2.utils.ZonedDateAsTime") var nextRising: String? = null,
                @SerializedName("next_setting") @Metadata(name = "下次日落", display = "cn.com.thinkwatch.ihass2.utils.ZonedDateAsTime") var nextSetting: String? = null,
                @SerializedName("last_triggered") @Metadata(name = "上次触发", display = "cn.com.thinkwatch.ihass2.utils.ZonedDateAsTime") var lastTriggered: String? = null,
                @SerializedName("space_free") @Metadata(name = "剩余空间", display = "cn.com.thinkwatch.ihass2.utils.SpaceArrayFormat") var spaceFree: List<Long>? = null,
                @SerializedName("volume") @Metadata(name = "音量", unit = "%") var volume: Float? = null,
                @SerializedName("channel") @Metadata(name = "频道") var channel: String? = null,
                @SerializedName("speed_list") var speedList: ArrayList<String>? = null,
                @SerializedName("speed") @Metadata(name = "风速") var speed: String? = null,
                @SerializedName("oscillating") @Metadata(name = "摇头") var oscillating: Boolean? = null,
                @SerializedName("direction") @Metadata(name = "方向") var direction: String? = null,
                @SerializedName("fan_speed_list") var fanSpeedList: ArrayList<String>? = null,
                @SerializedName("assumed_state") var assumedState: String? = null,
                @SerializedName("friendly_name") var friendlyName: String? = null,
                @SerializedName("id") var id: String? = null,
                @SerializedName("effect") var effect: String? = null,
                @SerializedName("fan_list") var fanList: ArrayList<String>? = null,
                @SerializedName("fan_modes") var fanModes: ArrayList<String>? = null,
                @SerializedName("effect_list") var effectList: ArrayList<String>? = null,
                @SerializedName("operation_list") var operationList: ArrayList<String>? = null,
                @SerializedName("hvac_modes") var hvacModes: ArrayList<String>? = null,
                @SerializedName("swing_list") var swingList: ArrayList<String>? = null,
                @SerializedName("swing_modes") var swingModes: ArrayList<String>? = null,
                @SerializedName("app_name") var appName: String? = null,
                @SerializedName("is_volume_muted") @Metadata(name = "静音") var isVolumeMuted: Boolean? = null,
                @SerializedName("volume_level") var volumeLevel: BigDecimal? = null,
                @SerializedName("entity_picture") var entityPicture: String? = null,
                @SerializedName("icon") var icon: String? = null,
                @SerializedName("title") var title: String? = null,
                @SerializedName("year") var year: Int? = null,
                @SerializedName("month") var month: Int? = null,
                @SerializedName("day") var day: Int? = null,
                @SerializedName("hour") var hour: Int? = null,
                @SerializedName("minute") var minute: Int? = null,
                @SerializedName("timestamp") var timestamp: String? = null,
                @SerializedName("has_date") var hasDate: Boolean? = null,
                @SerializedName("has_time") var hasTime: Boolean? = null,
                @SerializedName("device_class") var deviceClass: String? = null,
                @SerializedName("brightness") var brightness: BigDecimal? = null,
                @SerializedName("color_temp") var colorTemp: BigDecimal? = null,
                @SerializedName("rgb_color") var rgbColors: ArrayList<BigDecimal>? = null,
                @SerializedName("white_value") var whiteValue: BigDecimal? = null,
                @SerializedName("options") var options: ArrayList<String>? = null,
                @SerializedName("preview_url") var previewUrl: String? = null,
                @SerializedName("tts_sensor") var ttsSensor: String? = null,
                @SerializedName("order") var order: Int? = null,
                @SerializedName("auto") var auto: Boolean? = null,
                @SerializedName("hidden") var hidden: Boolean? = null,
                @SerializedName("view") var view: Boolean? = null,
                @SerializedName("name") var name: String? = null,
                @SerializedName("url") var url: String? = null,
                @SerializedName("initial") var initial: BigDecimal? = null,
                @SerializedName("code_format") var codeFormat: String? = null,
                @SerializedName("pattern") var pattern: String? = null,
                @SerializedName("max") var max: BigDecimal? = null,
                @SerializedName("min") var min: BigDecimal? = null,
                @SerializedName("current_position") var currentPosition: BigDecimal? = null,
                @SerializedName("current_tilt_position") var currentTiltPosition: BigDecimal? = null,
                @SerializedName("step") var step: BigDecimal? = null,
                @SerializedName("current_temperature") @Metadata(name = "当前温度", unit = "℃") var currentTemperature: BigDecimal? = null,
                @SerializedName("fan_mode")  @Metadata(name = "风扇模式") var fanMode: String? = null,
                @SerializedName("hvac_mode") @Metadata(name = "空调模式") var hvacMode: String? = null,
                @SerializedName("swing_mode") @Metadata(name = "摆风模式") var swingMode: String? = null,
                @SerializedName("load_power") @Metadata(name = "当前功率", unit = "W") var loadPower: String? = null,
                @SerializedName("fan_speed") @Metadata(name = "风扇速度") var fanSpeed: String? = null,
                @SerializedName("temperature") @Metadata(name = "设定温度", unit = "℃") var temperature: String? = null,
                @SerializedName("supported_features") var supportedFeatures: Int = 0,
                @SerializedName("aux_heat") var auxHeat: Boolean? = null,
                @SerializedName("away_mode") var awayMode: Boolean? = null,
                @SerializedName("max_temp") var maxTemp: BigDecimal? = null,
                @SerializedName("min_temp") var minTemp: BigDecimal? = null,
                @SerializedName("activity") var activity: String? = null,
                @SerializedName("provider") var provider: String? = null,
                @SerializedName("source_type") var sourceType: String? = null,
                @SerializedName("battery") var battery: String? = null,
                @SerializedName("gps_accuracy") var gpsAccuracy: BigDecimal? = null,
                @SerializedName("altitude") var altitude: BigDecimal? = null,
                @SerializedName("latitude") var latitude: BigDecimal? = null,
                @SerializedName("longitude") var longitude: BigDecimal? = null,
                @SerializedName("radius") var radius: BigDecimal? = null,
                @SerializedName("release_notes") var releaseNotes: Boolean? = null,
                @SerializedName("is_stateful") var isStateful: Boolean? = null,
                @SerializedName("ihass_state") var ihassState: KeyValues? = null,
                @SerializedName("ihass_icon") var ihassIcon: KeyValues? = null,
                @SerializedName("ihass_detail") var ihassDetail: String? = null,
                @SerializedName("ihass_total") var ihassTotal: String? = null,
                @SerializedName("ihass_detail_reduce") var ihassDetailReduce: Int? = null,
                @SerializedName("ihass_total_extra") var ihassTotalExtra: String? = null,
                @SerializedName("ihass_days") var ihassDays: Int? = null,
                @SerializedName("miio_channels") var channels: List<Int>? = null,
                @SerializedName("media_content_id") var mediaContentId: String? = null,
                @SerializedName("media_content_type") var mediaContentType: String? = null,
                @SerializedName("media_duration") var mediaDuration: Double? = null,
                @SerializedName("media_position") var mediaPosition: Double? = null,
                @SerializedName("media_title") var mediaTitle: String? = null,
                @SerializedName("media_artist") var mediaArtist: String? = null,
                @SerializedName("media_album_name") var mediaAlbumName: String? = null,
                @SerializedName("media_season") var mediaSeason: String? = null,
                @SerializedName("media_episode") var mediaEpisode: String? = null,
                @SerializedName("media_series_title") var mediaSeriesTitle: String? = null,
                @SerializedName("sound_mode_list") var soundModeList: ArrayList<String>? = null,
                @SerializedName("source_list") var sourceList: ArrayList<String>? = null,
                @SerializedName("source") var source: String? = null,
                @SerializedName("sound_mode") var soundMode: String? = null,
                @SerializedName("shuffle") var shuffle: Boolean? = null,
                @SerializedName("mode") var mode: String? = null,
                @SerializedName("message") @Metadata(name = "信息") var message: String? = null,
                @SerializedName("生活建议") @Metadata(name = "生活建议") var lifeSuggest: String? = null,
                @SerializedName("battery_level") @Metadata(name = "电量", unit = "%") var batteryLevel: Float? = null,
                @SerializedName("do_not_disturb") @Metadata(name = "免打扰模式") var doNotDistrub: String? = null,
                @SerializedName("do_not_disturb_start") @Metadata(name = "免打扰开始") var doNotDistrubStart: String? = null,
                @SerializedName("do_not_disturb_end") @Metadata(name = "免打扰结束") var doNotDistrubEnd: String? = null,
                @SerializedName("cleaning_time") @Metadata(name = "清扫时长", unit = "分钟") var cleaningTime: String? = null,
                @SerializedName("cleaned_area") @Metadata(name = "清扫区域", unit = "㎡") var cleanedArea: String? = null,
                @SerializedName("cleaning_count") @Metadata(name = "清扫次数", unit = "次") var cleaningCount: String? = null,
                @SerializedName("total_cleaned_area") @Metadata(name = "总清扫区域", unit = "㎡") var totalCleanedArea: String? = null,
                @SerializedName("total_cleaning_time") @Metadata(name = "总清扫时长", unit = "分钟") var totalCleaningTime: String? = null,
                @SerializedName("main_brush_left") @Metadata(name = "主刷剩余", unit = "小时") var mainBrushLeft: String? = null,
                @SerializedName("side_brush_left") @Metadata(name = "边刷剩余", unit = "小时") var sideBrushLeft: String? = null,
                @SerializedName("filter_left") @Metadata(name = "滤网剩余", unit = "小时") var filterLeft: String? = null,
                @SerializedName("unit_of_measurement") var unitOfMeasurement: String? = null)