package cn.com.thinkwatch.ihass2.model

import cn.com.thinkwatch.ihass2.utils.AlwaysListTypeAdapterFactory
import com.google.gson.annotations.JsonAdapter
import com.google.gson.annotations.SerializedName
import java.math.BigDecimal
import java.util.*

class Attribute(@SerializedName("entity_id") @JsonAdapter(AlwaysListTypeAdapterFactory::class) var entityIds: ArrayList<String>? = null,
                @SerializedName("next_dawn") @Metadata(name = "下次黎明", display = "cn.com.thinkwatch.ihass2.utils.ZonedDateAsTime") var nextDawn: String? = null,
                @SerializedName("next_dusk") @Metadata(name = "下次黄昏", display = "cn.com.thinkwatch.ihass2.utils.ZonedDateAsTime") var nextDusk: String? = null,
                @SerializedName("next_midnight") @Metadata(name = "下次午夜", display = "cn.com.thinkwatch.ihass2.utils.ZonedDateAsTime") var nextMidnight: String? = null,
                @SerializedName("next_noon") @Metadata(name = "下次正午", display = "cn.com.thinkwatch.ihass2.utils.ZonedDateAsTime") var nextNoon: String? = null,
                @SerializedName("next_rising") @Metadata(name = "下次日出", display = "cn.com.thinkwatch.ihass2.utils.ZonedDateAsTime") var nextRising: String? = null,
                @SerializedName("next_setting") @Metadata(name = "下次日落", display = "cn.com.thinkwatch.ihass2.utils.ZonedDateAsTime") var nextSetting: String? = null,
                @SerializedName("last_triggered") @Metadata(name = "上次触发", display = "cn.com.thinkwatch.ihass2.utils.ZonedDateAsTime") var lastTriggered: String? = null,
                @SerializedName("speed_list") var speedList: ArrayList<String>? = null,
                @SerializedName("fan_speed_list") var fanSpeedList: ArrayList<String>? = null,
                @SerializedName("assumed_state") var assumedState: String? = null,
                @SerializedName("friendly_name") var friendlyName: String? = null,
                @SerializedName("fan_list") var fanList: ArrayList<String>? = null,
                @SerializedName("operation_list") var operationList: ArrayList<String>? = null,
                @SerializedName("swing_list") var swingList: ArrayList<String>? = null,
                @SerializedName("app_name") var appName: String? = null,
                @SerializedName("is_volume_muted") @Metadata(name = "静音") var isVolumeMuted: Boolean? = null,
                @SerializedName("volume_level") var volumeLevel: BigDecimal? = null,
                @SerializedName("entity_picture") var entityPicture: String? = null,
                @SerializedName("icon") var icon: String? = null,
                @SerializedName("title") var title: String? = null,
                @SerializedName("year") var year: Int? = null,
                @SerializedName("month") var month: Int? = null,
                @SerializedName("day") var day: Int? = null,
                @SerializedName("hour") var hour: Int? = null,
                @SerializedName("minute") var minute: Int? = null,
                @SerializedName("timestamp") var timestamp: String? = null,
                @SerializedName("has_date") var hasDate: Boolean? = null,
                @SerializedName("has_time") var hasTime: Boolean? = null,
                @SerializedName("device_class") var deviceClass: String? = null,
                @SerializedName("brightness") var brightness: BigDecimal? = null,
                @SerializedName("color_temp") var colorTemp: BigDecimal? = null,
                @SerializedName("rgb_color") var rgbColors: ArrayList<BigDecimal>? = null,
                @SerializedName("options") var options: ArrayList<String>? = null,
                @SerializedName("preview_url") var previewUrl: String? = null,
                @SerializedName("tts_sensor") var ttsSensor: String? = null,
                @SerializedName("order") var order: Int? = null,
                @SerializedName("auto") var auto: Boolean? = null,
                @SerializedName("hidden") var hidden: Boolean? = null,
                @SerializedName("view") var view: Boolean? = null,
                @SerializedName("name") var name: String? = null,
                @SerializedName("initial") var initial: Int? = null,
                @SerializedName("code_format") var codeFormat: String? = null,
                @SerializedName("pattern") var pattern: String? = null,
                @SerializedName("max") var max: BigDecimal? = null,
                @SerializedName("min") var min: BigDecimal? = null,
                @SerializedName("step") var step: BigDecimal? = null,
                @SerializedName("current_temperature") @Metadata(name = "当前温度") var currentTemperature: BigDecimal? = null,
                @SerializedName("fan_mode") @Metadata(name = "风扇模式") var fanMode: String? = null,
                @SerializedName("operation_mode") @Metadata(name = "空调模式") var operationMode: String? = null,
                @SerializedName("swing_mode") @Metadata(name = "摆风模式") var swingMode: String? = null,
                @SerializedName("load_power") @Metadata(name = "当前功率") var loadPower: String? = null,
                @SerializedName("fan_speed") @Metadata(name = "风扇速度") var fanSpeed: String? = null,
                @SerializedName("temperature") @Metadata(name = "设定温度") var temperature: String? = null,
                @SerializedName("max_temp") var maxTemp: BigDecimal? = null,
                @SerializedName("min_temp") var minTemp: BigDecimal? = null,
                @SerializedName("activity") var activity: String? = null,
                @SerializedName("provider") var provider: String? = null,
                @SerializedName("source_type") var sourceType: String? = null,
                @SerializedName("battery") var battery: String? = null,
                @SerializedName("gps_accuracy") var gpsAccuracy: BigDecimal? = null,
                @SerializedName("altitude") var altitude: BigDecimal? = null,
                @SerializedName("latitude") var latitude: BigDecimal? = null,
                @SerializedName("longitude") var longitude: BigDecimal? = null,
                @SerializedName("radius") var radius: BigDecimal? = null,
                @SerializedName("release_notes") var releaseNotes: Boolean? = null,
                @SerializedName("is_stateful") var isStateful: Boolean? = null,
                @SerializedName("生活建议") @Metadata(name = "生活建议") var lifeSuggest: String? = null,
                @SerializedName("unit_of_measurement") var unitOfMeasurement: String? = null)